; Script generated by Inno Setup Compiler

#define MyAppSourceDir "..\\build\\windows\\x64\\runner\\Release"
#define MyAppIcon "..\\windows\\runner\\resources\\app_icon.ico"

[Setup]
AppName=Serverpod Toolbox
AppVersion=1.1.3
WizardStyle=modern
DefaultDirName={commonpf}\Serverpod Toolbox
DefaultGroupName=Serverpod Toolbox
OutputDir=.\Output
OutputBaseFilename=serverpod_toolbox_installer
Compression=lzma
SolidCompression=yes
SetupIconFile="{#MyAppIcon}"

[Files]
Source: "{#MyAppSourceDir}\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs

[Icons]
Name: "{group}\Serverpod Toolbox"; Filename: "{app}\serverpod_toolbox.exe"

[Run]
Filename: "{app}\serverpod_toolbox.exe"; Description: "Launch Serverpod Toolbox"; Flags: nowait postinstall
